### ISSUE TITLE
你mod怎么弄的呀，我复制过来也失败

### ISSUE THREAD

**Issue by Iloveidea** [purofle/Industrial-Craft-Mindustry#1]
你mod怎么弄的呀，我复制过来也失败，弄不出artifacts

**Comment by purofle** [comment]
> 你mod怎么弄的呀，我复制过来也失败，弄不出artifacts

有无报错

**Comment by Iloveidea** [comment]
> > 你mod怎么弄的呀，我复制过来也失败，弄不出artifacts
> 
> 有无报错

不用了，我加了
`    - name: Build mod jar gr
      run : chmod +x gradlew`
以后就能用了（但我还是不知道复制的为什么不能用
